version: '3.5'
services:
  php-apache-environment:
    image: r3v1/4_sekolah-docker
    container_name: php-apache
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./4_sekolah/html:/var/www/4_sekolah/html/
    ports: 
      - "8000:80"

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: rapor_lte
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8888:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db